#!/usr/bin/env python3
"""Courses v2 batch 2: deeper Swedish content for the remaining 5 courses.
Same format/helpers as batch 1. Updates the Swedish body only (en/es follow).
Emits supabase/migrations/20260620160000_courses_v2_batch2.sql
"""
import json, os

OUT = os.path.join(os.path.dirname(__file__), "..", "supabase", "migrations",
                   "20260620160000_courses_v2_batch2.sql")

def txt(s): return {"type": "text", "text": s}
def btxt(s): return {"type": "text", "marks": [{"type": "bold"}], "text": s}
def H(s):   return {"type": "heading", "attrs": {"level": 3}, "content": [txt(s)]}
def SUB(s): return {"type": "paragraph", "content": [btxt(s)]}
def P(s):   return {"type": "paragraph", "content": [txt(s)]}
def _li(parts): return {"type": "listItem", "content": [{"type": "paragraph", "content": parts}]}
def UL(items):
    lis = [_li([btxt(it[0] + ": "), txt(it[1])]) if isinstance(it, tuple) else _li([txt(it)]) for it in items]
    return {"type": "bulletList", "content": lis}
def OL(items):
    return {"type": "orderedList", "content": [_li([btxt(l + " – "), txt(r)]) for l, r in items]}
def QUOTE(lines):
    paras = [{"type": "paragraph", "content": ([btxt(s + " ")] if s else []) + [txt(t)]} for s, t in lines]
    return {"type": "blockquote", "content": paras}
BUILDERS = {"h": H, "sub": SUB, "p": P, "ul": UL, "ol": OL, "quote": QUOTE}
def doc(modules):
    content = []
    for mod in modules:
        for kind, payload in mod:
            content.append(BUILDERS[kind](payload))
    return json.dumps({"type": "doc", "content": content}, ensure_ascii=False)
def jdoc(modules): return "$j$" + doc(modules) + "$j$::jsonb"
def slit(s): return "'" + s.replace("'", "''") + "'"

COURSES = []
def course(title_sv, modules): COURSES.append((title_sv, modules))

# ════════════ 4. MÖTESBOKNING & KALLA SAMTAL ════════════
course("Mötesbokning & kalla samtal", [
 [("h","Modul 1 – Mindset och förberedelse"),
  ("sub","Varför det här avgör affären"),
  ("p","Kalla samtal är ett siffrespel innan det blir ett skickspel. Den som ringer förberedd, i fokuserade pass och med rätt inställning till nej bokar fler möten – inte för att hen är modigare, utan för att hen ringer mer och bättre. Målet med ett kallt samtal är inte att sälja, det är att boka mötet."),
  ("sub","Det här lär du dig"),
  ("ul",["Se nej som statistik, inte som personligt nederlag","Ringa i fokuserade pass med tydligt mål","Förbereda lista och manus så du slipper tänka under samtalet"]),
  ("sub","Så gör du"),
  ("ol",[("Sätt ett mål","t.ex. 20 samtal och 2 bokade möten på en timme."),
         ("Förbered listan","ha 20 kvalificerade företag och en observation per företag."),
         ("Ring i pass","stör inte med mejl eller annat – bara samtal."),
         ("Le när du ringer","det hörs i rösten och sänker tröskeln.")]),
  ("sub","Vanliga misstag"),
  ("ul",[("Undvik","att ta varje nej personligt – det bromsar dig."),
         ("Undvik","att ringa oförberedd utan observation."),
         ("Gör","att mäta dina pass så du ser din utveckling.")]),
  ("sub","Öva"),
  ("p","Förbered en ringlista på 20 företag med en observation per företag inför nästa pass."),
  ("p","Facit: en bra observation är konkret och specifik för just dem, t.ex. svag Google-synlighet eller daterad sajt.")],
 [("h","Modul 2 – Öppningen och kroken"),
  ("sub","Varför det här avgör affären"),
  ("p","De första tio sekunderna avgör om kunden lyssnar eller lägger på. En vass öppning respekterar kundens tid, väcker nyfikenhet med en konkret krok och slutar med en fråga – inte en monolog."),
  ("sub","Det här lär du dig"),
  ("ul",["Presentera dig kort och be om 30 sekunder","Haka på en konkret observation","Avsluta öppningen med en fråga"]),
  ("sub","Strukturen"),
  ("ol",[("Hälsa och be om tid","'Hej [namn], [ditt namn] från Applabbet – ge mig 30 sekunder?'"),
         ("Kroken","'Jag såg att ni inte syns på [sökord] och tänkte att det kan finnas kunder att hämta.'"),
         ("Frågan","'Hur jobbar ni med att få in nya kunder digitalt idag?'")]),
  ("sub","Ordagrant exempel"),
  ("quote",[(None,"\"Hej Anna, det är Robert från Applabbet. Jag ringer kort och vet att jag stör – ger du mig 30 sekunder så berättar jag varför, sen får du säga om det är intressant?\"")]),
  ("sub","Vanliga misstag"),
  ("ul",[("Undvik","en lång monolog om er själva."),
         ("Undvik","generiska krokar som passar alla."),
         ("Gör","att lyssna mer än du pratar efter frågan.")]),
  ("sub","Öva"),
  ("p","Skriv din egen 30-sekundersöppning och säg den högt tio gånger tills den sitter."),
  ("p","Facit: en bra öppning är kort, har en konkret krok och slutar med en öppen fråga.")],
 [("h","Modul 3 – Hantera artiga avfärdningar"),
  ("sub","Varför det här avgör affären"),
  ("p","'Skicka info' och 'vi har inget behov' är sällan ett riktigt nej – det är reflexer. Den som behåller initiativet utan att bli påträngande förvandlar avfärdningen till ett bokat möte."),
  ("sub","Det här lär du dig"),
  ("ul",["Bemöta 'skicka info' utan att tappa initiativet","Ta dig förbi en gatekeeper artigt","Kvalificera medan du behåller styrfarten"]),
  ("sub","Så gör du"),
  ("ol",[("Acceptera","'Absolut, jag skickar gärna.'"),
         ("Kvalificera","'För att det ska bli relevant – vad är viktigast: fler kunder, modernare sajt eller bättre synlighet?'"),
         ("Behåll initiativet","'Då skickar jag rätt sak och stämmer av på fredag – passar förmiddagen?'")]),
  ("sub","Gatekeepern"),
  ("ul",[("Var en allierad","behandla växeln/assistenten som en hjälp, inte ett hinder."),
         ("Var rak","'Kan du hjälpa mig till den som ansvarar för er hemsida?'")]),
  ("sub","Vanliga misstag"),
  ("ul",[("Undvik","att tacka och lägga på vid 'skicka info'."),
         ("Undvik","att försöka 'lura' dig förbi gatekeepern."),
         ("Gör","att alltid föreslå en konkret återkoppling.")]),
  ("sub","Öva"),
  ("p","Skriv ditt svar på 'skicka info så återkommer vi' som behåller initiativet."),
  ("p","Facit: acceptera, kvalificera med en fråga och boka en kort återkoppling.")],
 [("h","Modul 4 – Boka mötet och mät"),
  ("sub","Varför det här avgör affären"),
  ("p","Ett samtal utan en bokad tid är ett misslyckat samtal, oavsett hur trevligt det var. Och utan att mäta dina siffror vet du inte vad du ska förbättra. De flesta möten bokas dessutom på andra eller tredje försöket – uppföljning är halva jobbet."),
  ("sub","Det här lär du dig"),
  ("ul",["Föreslå tid så det är lätt att svara ja","Bekräfta tiden direkt","Mäta din tratt och förbättra delarna"]),
  ("sub","Så gör du"),
  ("ol",[("Föreslå två tider","'Passar tisdag 10 eller torsdag 14?' i stället för 'när passar det?'"),
         ("Bekräfta direkt","lägg in i kalender och skicka en mötesinbjudan på en gång."),
         ("Följ upp","de flesta möten bokas på försök två eller tre – ge inte upp efter ett."),
         ("Mät tratten","räkna samtal, kontakter och bokade möten.")]),
  ("sub","Vanliga misstag"),
  ("ul",[("Undvik","den öppna frågan 'när passar det?'."),
         ("Undvik","att inte bekräfta tiden skriftligt."),
         ("Gör","att logga varje samtal och möte i CRM:t.")]),
  ("sub","Öva"),
  ("p","Boka tre möten den här veckan och räkna ut din bokningsgrad (möten delat med samtal)."),
  ("p","Facit: 20 samtal som ger 2 möten = 10 procents bokningsgrad – använd den för att sätta dagliga mål.")]],
)

# ════════════ 5. DIGITAL SPETSKUNSKAP: SEO & GEO ════════════
course("Digital spetskunskap: SEO & GEO", [
 [("h","Modul 1 – Så funkar SEO"),
  ("sub","Varför det här avgör affären"),
  ("p","SEO och GEO är de tjänster som ger återkommande intäkt och syns svart på vitt i rapporter. Men du kan bara sälja det du kan förklara enkelt. Kan du på 30 sekunder få en kund att förstå varför SEO är värt pengarna har du ett försprång."),
  ("sub","Det här lär du dig"),
  ("ul",["Förklara SEO enkelt för en kund","Förklara varför trafiken är 'gratis' och långsiktig","Sätta rätt förväntan på tid till resultat"]),
  ("sub","Grunderna att kunna"),
  ("ol",[("Vad det är","SEO gör att en sajt rankar högre på Google."),
         ("Vad det bygger på","on-page (titlar, innehåll, fart), content och länkar."),
         ("Tidshorisont","långsiktigt – oftast resultat på 3–6 månader."),
         ("Fördelen","organisk trafik kostar inget per klick och försvinner inte när du slutar annonsera.")]),
  ("sub","Ordagrant exempel"),
  ("quote",[(None,"\"Era kunder googlar redan det ni säljer. SEO avgör om de hittar er eller konkurrenten – och till skillnad från annonser kostar varje klick ingenting.\"")]),
  ("sub","Vanliga misstag"),
  ("ul",[("Undvik","att lova en specifik Google-placering."),
         ("Undvik","att tala om SEO som en engångsinsats."),
         ("Gör","att sätta förväntan på 3–6 månader tidigt.")]),
  ("sub","Öva"),
  ("p","Förklara SEO för en kollega på 30 sekunder utan facktermer."),
  ("p","Facit: en bra förklaring säger vad det är, vad det ger och ungefär när – på vardagssvenska.")],
 [("h","Modul 2 – Nyckelord och teknisk grund"),
  ("sub","Varför det här avgör affären"),
  ("p","Rätt nyckelord styr hela SEO-arbetet, och tekniska grunder avgör om Google ens vill ranka sajten. Du behöver inte vara tekniker, men du måste kunna prata om det med trovärdighet."),
  ("sub","Det här lär du dig"),
  ("ul",["Hitta nyckelord med köpavsikt","Förstå de tekniska grunder som påverkar ranking","Koppla det till varför vi bygger i Astro/React"]),
  ("sub","Så gör du"),
  ("ol",[("Utgå från kundens språk","kombinera tjänst och plats: 'takläggare Göteborg'."),
         ("Leta köpavsikt","'pris takbyte' säljer, 'vad är ett tak' gör det inte."),
         ("Kolla tekniken","fart, mobilanpassning, HTTPS och tydlig struktur."),
         ("Knyt till oss","därför bygger vi snabba sajter i Astro/React.")]),
  ("sub","Vanliga misstag"),
  ("ul",[("Undvik","att gissa nyckelord utifrån ditt eget språk."),
         ("Undvik","att ignorera laddtid och mobil."),
         ("Gör","att testa en kunds sajt i Googles PageSpeed inför mötet.")]),
  ("sub","Öva"),
  ("p","Lista fem nyckelord en kund i en vald bransch skulle googla, och markera vilka som visar köpavsikt."),
  ("p","Facit: köpavsikt finns i ord som 'pris', 'köpa', 'offert', 'nära mig' – inte i rena faktasökningar.")],
 [("h","Modul 3 – GEO och AI-synlighet"),
  ("sub","Varför det här avgör affären"),
  ("p","Allt fler frågar ChatGPT och Perplexity i stället för Google. Syns ni inte där finns ni inte i svaret – och konkurrenterna är oftast inte med än. Det är ett försprång som bara finns att ta just nu."),
  ("sub","Det här lär du dig"),
  ("ul",["Förklara vad GEO är och varför det är nytt","Visa varför det är ett 'first mover'-läge","Förstå hur AI väljer källor"]),
  ("sub","Så gör du"),
  ("ol",[("Förklara enkelt","GEO handlar om att bli omnämnd och rekommenderad i AI-sök."),
         ("Visa nuläget","fråga ChatGPT om kundens bransch och se vilka som nämns."),
         ("Optimera","tydligt innehåll, vanliga frågor och omnämnanden på andra sajter."),
         ("Sälj försprånget","konkurrenterna syns inte än – var först.")]),
  ("sub","Ordagrant exempel"),
  ("quote",[(None,"\"Hur beskriver ChatGPT ert företag idag? Om svaret är tomt eller fel är det en möjlighet – era konkurrenter syns inte heller än, så den som agerar nu får försprånget.\"")]),
  ("sub","Vanliga misstag"),
  ("ul",[("Undvik","att framställa GEO som magi – det är mätbart arbete."),
         ("Undvik","att säga 'det är för tidigt' – tidigt är just poängen."),
         ("Gör","att visa ett konkret AI-svar i mötet.")]),
  ("sub","Öva"),
  ("p","Fråga ett AI-verktyg 'bästa [bransch] i [stad]' och notera vilka som nämns och inte."),
  ("p","Facit: poängen är att visa kunden att de saknas där deras kunder börjar fråga.")],
 [("h","Modul 4 – Mätbarhet: sälj nuläge mot potential"),
  ("sub","Varför det här avgör affären"),
  ("p","Det som mäts går att sälja. Skepsis mot SEO och GEO bemöts inte med löften utan med data: ranking, trafik och leads svart på vitt varje månad. Och köplust skapas i glappet mellan var kunden står idag och var de kan vara."),
  ("sub","Det här lär du dig"),
  ("ul",["Använda rapporter som ditt starkaste säljargument","Visa nuläge mot potential","Avsluta med ett konkret nästa steg"]),
  ("sub","Så gör du"),
  ("ol",[("Mät allt","ranking, trafik och leads i en tydlig månadsrapport."),
         ("Visa nuläget","en kostnadsfri synlighetsanalys: var rankar de idag?"),
         ("Måla potentialen","'Här är planen för att nå topp tre på tre månader.'"),
         ("Föreslå nästa steg","boka en uppföljning eller en analys.")]),
  ("sub","Vanliga misstag"),
  ("ul",[("Undvik","att bemöta skepsis med fler löften."),
         ("Undvik","att visa data utan att koppla den till leads och kunder."),
         ("Gör","att alltid avsluta med en synlighetsanalys eller ett möte.")]),
  ("sub","Öva"),
  ("p","Gör en snabb synlighetskoll på ett företag och formulera glappet mellan nuläge och potential i två meningar."),
  ("p","Facit: en stark formulering säger var de står idag och vad som är möjligt – och bjuder in till nästa steg.")]],
)

# ════════════ 6. PRODUKTMÄSTAREN ════════════
course("Produktmästaren", [
 [("h","Modul 1 – Hemsidor och appar"),
  ("sub","Varför det här avgör affären"),
  ("p","Kan du paketen utantill kan du snabbt matcha rätt lösning mot kundens behov och budget – och då känns du som en rådgivare, inte en säljare. Utgå alltid från behovet, inte produkten."),
  ("sub","Det här lär du dig"),
  ("ul",["Skilja på landningssida, hemsida, MVP, webbapp och mobilapp","Veta ungefärligt pris för varje","Matcha rätt produkt mot behovet"]),
  ("sub","Produkterna och när"),
  ("ol",[("Landningssida (från 9 000 kr)","en sida för kampanjer och leads."),
         ("Företagshemsida (18 000 kr)","upp till sju sidor med eget CMS – vårt populäraste."),
         ("MVP (från 29 000 kr)","validera en idé på 4–6 veckor, kunden äger källkoden."),
         ("Webbapp (från 49 000 kr)","inloggning, data och automatik."),
         ("Mobilapp (från 79 000 kr)","iOS och Android från samma kodbas.")]),
  ("sub","Vanliga misstag"),
  ("ul",[("Undvik","att föreslå en hemsida när behovet är en webbapp (inloggning/data)."),
         ("Undvik","att rabbla alla produkter."),
         ("Gör","att fråga 'ska användaren logga in eller mata in data?' för att avgöra.")]),
  ("sub","Öva"),
  ("p","Para ihop fem kundbehov med rätt produkt och motivera kort."),
  ("p","Facit: leads → landningssida/hemsida; validera idé → MVP; intern process → webbapp; finnas i fickan → mobilapp.")],
 [("h","Modul 2 – E-handel"),
  ("sub","Varför det här avgör affären"),
  ("p","E-handel är återkommande intäkt (uppstart plus månadsavgift) och en lösning som växer med kunden. Att välja rätt nivå handlar om sortiment och integrationsbehov."),
  ("sub","Det här lär du dig"),
  ("ul",["Skilja på Start, Plus och Pro","Veta vad varje nivå löser","Välja nivå efter sortiment och integrationer"]),
  ("sub","Nivåerna"),
  ("ol",[("Start (från 19 000 kr + 1 490 kr/mån)","ca 100 produkter, Klarna/Stripe, frakt, mobil."),
         ("Plus (från 35 000 kr + 2 490 kr/mån)","ca 1 000 produkter, rabattkoder, kundkonton, nyhetsbrev – populärast."),
         ("Pro (från 59 000 kr + 4 900 kr/mån)","obegränsat, ERP-integration (Fortnox/Visma), B2B-priser, flera språk.")]),
  ("sub","Vanliga misstag"),
  ("ul",[("Undvik","att sälja Pro till en liten butik – eller Start till ett stort B2B-bolag."),
         ("Undvik","att glömma månadsavgiften i kalkylen."),
         ("Gör","att fråga om antal produkter och affärssystem för att välja nivå.")]),
  ("sub","Öva"),
  ("p","Motivera vilken nivå tre olika butiker borde ha (liten lokal, växande varumärke, grossist med Fortnox)."),
  ("p","Facit: liten → Start; växande → Plus; grossist med ERP och B2B → Pro.")],
 [("h","Modul 3 – SEO, GEO och design som löpande intäkt"),
  ("sub","Varför det här avgör affären"),
  ("p","Engångsprojekt ger en faktura; löpande tjänster ger en relation och förutsägbar intäkt. SEO, GEO och designpartner är dessutom den naturliga uppföljningen efter en levererad sajt."),
  ("sub","Det här lär du dig"),
  ("ul",["Sälja de löpande tjänsterna","Veta prisnivåerna","Se uppföljningstillfället efter en leverans"]),
  ("sub","Tjänsterna"),
  ("ol",[("SEO (från 4 900 kr/mån)","synlighet på Google och långsiktig trafik."),
         ("GEO (från 6 900 kr/mån)","AI-synlighet – ett tidigt försprång."),
         ("Designpartner (från 9 000 kr/mån)","löpande design utan att anställa."),
         ("Logotyp och varumärke (från 12 000 kr)","en bra dörröppnare före en sajt.")]),
  ("sub","Vanliga misstag"),
  ("ul",[("Undvik","att se en levererad sajt som slutet på affären."),
         ("Undvik","att sälja löpande tjänster som engångsjobb."),
         ("Gör","att föreslå SEO/GEO som nästa steg vid varje leverans.")]),
  ("sub","Öva"),
  ("p","Föreslå en löpande tjänst till tre tidigare kunder och motivera varför just nu."),
  ("p","Facit: en levererad sajt utan trafik är en tyst butik – SEO/GEO är det naturliga nästa steget.")],
 [("h","Modul 4 – Teknikval och kombinationspaket"),
  ("sub","Varför det här avgör affären"),
  ("p","Rätt teknik gör kunden snabb, säker och billig i drift – och fel teknik skapar problem i flera år. Och smarta kombinationspaket höjer ordervärdet och ger kunden en helhet."),
  ("sub","Det här lär du dig"),
  ("ul",["Välja mellan statiskt (Astro) och dynamiskt (React)","Sätta ihop kombinationspaket","Räkna hem värdet med ROI"]),
  ("sub","Teknikval"),
  ("ol",[("Astro (statiskt)","för sajter som mest presenterar: hantverk, restaurang, konsult."),
         ("React (dynamiskt)","när det krävs inloggning, bokning eller realtidsdata."),
         ("Tumregel","'ska användaren logga in eller mata in data?' → React, annars Astro.")]),
  ("sub","Kombinationspaket"),
  ("ul",[("Startpaket","hemsida + SEO."),
         ("Tillväxtpaket","hemsida + SEO + GEO."),
         ("MVP-paket","MVP + designpartner.")]),
  ("sub","Vanliga misstag"),
  ("ul",[("Undvik","att börja i tekniken i stället för i behovet."),
         ("Undvik","att sälja delar när en helhet passar bättre."),
         ("Gör","att räkna hem priset mot vad en kund är värd.")]),
  ("sub","Öva"),
  ("p","Para ihop tre kunder med rätt teknikval och föreslå ett kombinationspaket till var och en."),
  ("p","Facit: presenterande verksamhet → Astro; bokning/portal → React; alltid komplettera med SEO/GEO.")]],
)

# ════════════ 7. STORYTELLING & PITCH ════════════
course("Storytelling & pitch", [
 [("h","Modul 1 – Strukturen: problem, lösning, resultat"),
  ("sub","Varför det här avgör affären"),
  ("p","Människor minns berättelser, inte funktionslistor. En pitch som börjar i kundens problem, visar lösningen och målar resultatet fastnar – och får kunden att tänka 'jag måste ha detta'. Du säljer förändringen, från hur det är nu till hur det blir."),
  ("sub","Det här lär du dig"),
  ("ul",["Strukturera en pitch som fastnar","Sälja förändringen, inte funktionerna","Börja i problemet"]),
  ("sub","Strukturen"),
  ("ol",[("Problem","börja i kundens smärta, gärna med deras egna ord."),
         ("Lösning","visa hur ni löser just det – kort och konkret."),
         ("Resultat","måla upp hur det blir efteråt.")]),
  ("sub","Ordagrant exempel"),
  ("quote",[(None,"\"Idag tappar ni kunder till en konkurrent som syns bättre (problem). Med en ny sajt och SEO hittar rätt kunder er i stället (lösning). Redan första månaden börjar förfrågningarna komma in (resultat).\"")]),
  ("sub","Vanliga misstag"),
  ("ul",[("Undvik","att börja i er själva eller i tekniken."),
         ("Undvik","att rabbla funktioner."),
         ("Gör","att alltid avsluta i ett konkret resultat.")]),
  ("sub","Öva"),
  ("p","Skriv en pitch i tre meningar enligt problem, lösning, resultat för en valfri kund."),
  ("p","Facit: en mening per del, och resultatet ska kännas konkret och önskvärt.")],
 [("h","Modul 2 – Kundens egna ord och hjälteresan"),
  ("sub","Varför det här avgör affären"),
  ("p","Den bästa pitchen ekar det kunden själv sagt – då känns den gjord för dem. Och i en bra berättelse är kunden hjälten och du guiden, aldrig tvärtom."),
  ("sub","Det här lär du dig"),
  ("ul",["Spegla kundens nyckelord","Göra kunden till hjälten","Positionera dig som guiden"]),
  ("sub","Så gör du"),
  ("ol",[("Anteckna","fånga kundens exakta uttryck i behovsanalysen."),
         ("Spegla","använd orden ordagrant i pitchen."),
         ("Sätt kunden i centrum","'Ni vill nå dit – så här tar vi er dit, steg för steg.'")]),
  ("sub","Ordagrant exempel"),
  ("quote",[(None,"\"Du sa att tid är er flaskhals. Det här tar bort det manuella jobbet så ni kan lägga tiden där den gör mest nytta.\"")]),
  ("sub","Vanliga misstag"),
  ("ul",[("Undvik","att prata mest om er själva och era priser."),
         ("Undvik","att byta ut kundens ord mot din egen jargong."),
         ("Gör","att låta kunden vara huvudpersonen i berättelsen.")]),
  ("sub","Öva"),
  ("p","Ta tre citat från en kund och bygg en mening kring varje som speglar deras ord."),
  ("p","Facit: meningen ska innehålla kundens eget uttryck och koppla det till en lösning.")],
 [("h","Modul 3 – Konkreta bevis och socialt bevis"),
  ("sub","Varför det här avgör affären"),
  ("p","Abstrakta löften övertygar ingen. Siffror, exempel och referenser bygger förtroende snabbt – människor litar på andra människor och på det som går att mäta."),
  ("sub","Det här lär du dig"),
  ("ul",["Göra värdet trovärdigt med siffror","Använda case och omdömen","Visa hellre än att berätta"]),
  ("sub","Så gör du"),
  ("ol",[("Räkna i kunder","'En extra kund i månaden betalar sajten.'"),
         ("Visa ett case","'En liknande kund fördubblade sina förfrågningar på tre månader.'"),
         ("Använd omdömen","ett kort citat från en nöjd kund slår dina egna påståenden.")]),
  ("sub","Vanliga misstag"),
  ("ul",[("Undvik","svepande superlativ utan bevis."),
         ("Undvik","att bara berätta i stället för att visa."),
         ("Gör","att alltid ha tre konkreta bevis redo.")]),
  ("sub","Öva"),
  ("p","Samla tre konkreta bevis (en siffra, ett case och ett omdöme) du kan använda i en pitch."),
  ("p","Facit: bevisen ska vara specifika och mätbara, inte allmänna påståenden.")],
 [("h","Modul 4 – Avsluta med en fråga och ord som säljer"),
  ("sub","Varför det här avgör affären"),
  ("p","En pitch som slutar i tystnad tappar farten. Avslutar du i stället med en fråga som öppnar nästa steg behåller du initiativet. Och enkla, konkreta ord slår jargong varje gång."),
  ("sub","Det här lär du dig"),
  ("ul",["Avsluta pitchen med en fråga","Välja ord som säljer i stället för jargong","Föra samtalet mot ett konkret nästa steg"]),
  ("sub","Så gör du"),
  ("ol",[("Avsluta öppet","'Ska jag ta fram ett förslag så går vi igenom det på fredag?'"),
         ("Välj enkla ord","säg 'fler kunder' i stället för 'ökad konvertering'."),
         ("Var specifik","undvik svepande superlativ – peka på ett konkret resultat.")]),
  ("sub","Ord som säljer mot ord som dödar"),
  ("ul",[("Säg","'ni får fler förfrågningar'."),
         ("Undvik","'vi maximerar er digitala potential'.")]),
  ("sub","Vanliga misstag"),
  ("ul",[("Undvik","att avsluta med en prislista i stället för en fråga."),
         ("Undvik","facktermer kunden inte använder."),
         ("Gör","att alltid leda mot ett möte eller en offert.")]),
  ("sub","Öva"),
  ("p","Skriv tre avslutsfrågor som leder mot ett möte eller en offert."),
  ("p","Facit: en bra avslutsfråga är lätt att säga ja till och öppnar nästa konkreta steg.")]],
)

# ════════════ 8. CRM-MÄSTAREN ════════════
course("CRM-mästaren", [
 [("h","Modul 1 – Lägg in och jobba leads"),
  ("sub","Varför det här avgör affären"),
  ("p","En lead som inte finns i CRM:t glöms bort – och en glömd lead är en förlorad affär. CRM:t är ditt nav: här lägger du in leads, loggar samtal och möten och håller koll på dina affärer."),
  ("sub","Det här lär du dig"),
  ("ul",["Skapa leads i rätt ögonblick","Fylla i dem ordentligt","Logga direkt efter varje kontakt"]),
  ("sub","Så gör du"),
  ("ol",[("Skapa direkt","lägg in leaden så fort du ser en möjlighet."),
         ("Fyll i ordentligt","företagsnamn, kontakt och din observation."),
         ("Logga efter samtal","skriv ner vad som sades och nästa steg medan det är färskt.")]),
  ("sub","Vanliga misstag"),
  ("ul",[("Undvik","att skapa leaden 'sen' – den glöms bort."),
         ("Undvik","att bara skriva företagsnamn utan kontext."),
         ("Gör","att logga direkt efter varje kontakt.")]),
  ("sub","Öva"),
  ("p","Lägg in fem leads och fyll i alla fält ordentligt, med en observation per lead."),
  ("p","Facit: en komplett lead har företag, kontakt, din observation och ett bokat nästa steg.")],
 [("h","Modul 2 – Uppgifter, möten och alltid ett nästa steg"),
  ("sub","Varför det här avgör affären"),
  ("p","En lead utan nästa steg dör. Uppgifter och möten med datum gör att systemet påminner dig – det är skillnaden mellan att jaga och att ha kontroll."),
  ("sub","Det här lär du dig"),
  ("ul",["Använda uppgifter och möten med datum","Avsluta varje kontakt med ett nästa steg","Lita på systemet i stället för minnet"]),
  ("sub","Så gör du"),
  ("ol",[("Boka nästa steg","avsluta varje kontakt med en bokad uppgift eller ett möte."),
         ("Sätt datum","så systemet påminner dig i tid."),
         ("Lovade du återkomma?","lägg en uppgift direkt så det inte glöms.")]),
  ("sub","Ordagrant exempel"),
  ("quote",[(None,"\"Innan ni avslutar samtalet: nästa steg är att jag tar fram ett förslag – ska vi säga att vi stämmer av på fredag klockan 10?\"")]),
  ("sub","Vanliga misstag"),
  ("ul",[("Undvik","att lita på minnet i stället för CRM:t."),
         ("Undvik","att avsluta en kontakt utan nästa steg."),
         ("Gör","att alltid sätta ett datum.")]),
  ("sub","Öva"),
  ("p","Skapa en uppgift med datum för varje aktiv lead du har just nu."),
  ("p","Facit: varje aktiv lead ska ha exakt ett tydligt nästa steg med ett datum.")],
 [("h","Modul 3 – Pipeline-stadier och daglig rutin"),
  ("sub","Varför det här avgör affären"),
  ("p","Pipeline är inte en lista – det är affärer i rörelse. En enkel daglig rutin gör att inget faller mellan stolarna och att du alltid vet vad du ska göra härnäst."),
  ("sub","Det här lär du dig"),
  ("ul",["Flytta affärer genom stadierna","Bygga en daglig rutin","Se var det stockar sig"]),
  ("sub","Stadierna"),
  ("ol",[("Ny lead","nyss inlagd, ej kontaktad."),
         ("Kontaktad","första kontakt tagen."),
         ("Möte bokat / Offert skickad","affären rör sig framåt."),
         ("Vunnen eller förlorad","stäng affären och notera varför.")]),
  ("sub","Daglig rutin"),
  ("ul",[("Morgon","kolla dagens uppgifter och möten."),
         ("Dagen","ring, boka och jobba av."),
         ("Kväll","logga och planera morgondagen.")]),
  ("sub","Vanliga misstag"),
  ("ul",[("Undvik","att låta leads ligga kvar i samma stadium i veckor."),
         ("Undvik","att hoppa över den dagliga genomgången."),
         ("Gör","att ge varje lead ett aktuellt stadium.")]),
  ("sub","Öva"),
  ("p","Sätt rätt stadium på varje aktiv lead och skriv din egen tre-stegs dagsrutin."),
  ("p","Facit: en offert som legat i 'skickad' i två veckor behöver en uppföljning – inte glömmas.")],
 [("h","Modul 4 – Rapporter, nyckeltal och Sandbox"),
  ("sub","Varför det här avgör affären"),
  ("p","Det du mäter kan du förbättra. Siffrorna visar var det stockar sig: får du många möten men inga avslut är det pitchen eller offerten som skaver. Och osäker på en funktion? Öva i Sandbox där inget sparas."),
  ("sub","Det här lär du dig"),
  ("ul",["Följa de nyckeltal som driver resultat","Tolka var i tratten det stockar sig","Öva tryggt i Sandbox"]),
  ("sub","Nyckeltal att följa"),
  ("ol",[("Samtal","hur mycket aktivitet du har."),
         ("Bokade möten","hur väl du bokar."),
         ("Skickade offerter","hur många affärer som mognar."),
         ("Vunna affärer","hur väl du stänger.")]),
  ("sub","Vanliga misstag"),
  ("ul",[("Undvik","att jobba utan att titta på dina siffror."),
         ("Undvik","att testa nya funktioner på skarpa kunddata."),
         ("Gör","att öva i Sandbox-fliken först – där sparas inget.")]),
  ("sub","Öva"),
  ("p","Lista de fyra nyckeltal du vill följa varje vecka och gå igenom varje flik i Sandbox en gång."),
  ("p","Facit: många möten men inga avslut pekar på pitch eller offert; få möten pekar på prospektering eller bokning.")]],
)

# ── Emit body-only UPDATEs ──────────────────────────────────────────────────
parts = []
for title_sv, modules in COURSES:
    parts.append(f"""UPDATE public.training_items ti
SET body = {jdoc(modules)}
FROM public.training_categories cat
WHERE ti.category_id = cat.id AND cat.slug = 'kurser'
  AND ti.title = {slit(title_sv)};""")

sql = ("-- Courses v2 batch 2 (deeper format): replace the Swedish body of the\n"
       "-- remaining 5 courses. en/es translations handled in a follow-up pass.\n\n"
       + "\n\n".join(parts) + "\n")
with open(OUT, "w", encoding="utf-8") as f:
    f.write(sql)

import re
for d in re.findall(r"\$j\$(.*?)\$j\$", sql, re.S):
    json.loads(d)
print("wrote", os.path.basename(OUT), "with", len(COURSES), "courses")
