-- Seed FAQ (sv/en/es) into the FAQ category. Each item is a question (title)
-- with its answer (body). Skips items whose title already exists.
INSERT INTO public.training_items
  (category_id, title, title_en, title_es, body, body_en, body_es, sort_order, is_published)
SELECT cat.id, v.title, v.title_en, v.title_es, v.body, v.body_en, v.body_es, v.ord, true
FROM (VALUES
  ('Vad kostar en hemsida?', 'How much does a website cost?', '¿Cuánto cuesta una web?', $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Det beror på typ: landningssida från 9 000 kr, företagshemsida 18 000 kr, och en dynamisk sajt eller webbapp från 49 000 kr. Vi tar fram en offert efter era behov."}]}]}$j$::jsonb, $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "It depends on the type: a landing page from SEK 9,000, a business website SEK 18,000, and a dynamic site or web app from SEK 49,000. We prepare a quote based on your needs."}]}]}$j$::jsonb, $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Depende del tipo: una página de aterrizaje desde 9 000 SEK, una web corporativa 18 000 SEK, y un sitio dinámico o aplicación web desde 49 000 SEK. Preparamos un presupuesto según vuestras necesidades."}]}]}$j$::jsonb, 1),
  ('Hur lång tid tar det?', 'How long does it take?', '¿Cuánto tiempo lleva?', $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Landningssida ofta inom en vecka, företagshemsida 2–4 veckor och MVP 4–6 veckor. Webb- och mobilappar sätts efter omfång."}]}]}$j$::jsonb, $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "A landing page often within a week, a business website 2–4 weeks and an MVP 4–6 weeks. Web and mobile apps are set by scope."}]}]}$j$::jsonb, $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Una página de aterrizaje a menudo en una semana, una web corporativa 2–4 semanas y un MVP 4–6 semanas. Las apps web y móviles se ajustan según el alcance."}]}]}$j$::jsonb, 2),
  ('Äger vi sajten och koden?', 'Do we own the site and the code?', '¿Somos dueños del sitio y del código?', $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Ja. Ni äger er sajt, och vid MVP eller app äger ni källkoden."}]}]}$j$::jsonb, $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Yes. You own your site, and with an MVP or app you own the source code."}]}]}$j$::jsonb, $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Sí. Sois dueños de vuestro sitio, y con un MVP o app sois dueños del código fuente."}]}]}$j$::jsonb, 3),
  ('Kan vi uppdatera innehållet själva?', 'Can we update the content ourselves?', '¿Podemos actualizar el contenido nosotros mismos?', $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Ja – hemsidor och e-handel har eget CMS, inga utvecklarkunskaper krävs."}]}]}$j$::jsonb, $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Yes – websites and e-commerce come with their own CMS, no developer skills needed."}]}]}$j$::jsonb, $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Sí: las webs y el e-commerce incluyen su propio CMS, sin necesidad de conocimientos de desarrollo."}]}]}$j$::jsonb, 4),
  ('Ingår SEO?', 'Is SEO included?', '¿Incluye SEO?', $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Grundläggande on-page SEO ingår i hemsidor. Löpande SEO (Start eller Tillväxt) är ett separat paket."}]}]}$j$::jsonb, $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Basic on-page SEO is included in websites. Ongoing SEO (Start or Growth) is a separate package."}]}]}$j$::jsonb, $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "El SEO on-page básico se incluye en las webs. El SEO continuo (Start o Crecimiento) es un paquete aparte."}]}]}$j$::jsonb, 5),
  ('Vad är skillnaden på SEO och GEO?', 'What''s the difference between SEO and GEO?', '¿Cuál es la diferencia entre SEO y GEO?', $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "SEO handlar om att synas på Google. GEO handlar om att synas och rekommenderas i AI-sök som ChatGPT och Perplexity."}]}]}$j$::jsonb, $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "SEO is about being seen on Google. GEO is about being seen and recommended in AI search like ChatGPT and Perplexity."}]}]}$j$::jsonb, $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "El SEO trata de aparecer en Google. El GEO trata de aparecer y ser recomendado en buscadores de IA como ChatGPT y Perplexity."}]}]}$j$::jsonb, 6),
  ('Bygger ni på WordPress eller Shopify?', 'Do you build on WordPress or Shopify?', '¿Construís en WordPress o Shopify?', $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Nej – vi bygger på modern teknik (Astro/React) och egen e-handelsplattform. Snabbare, säkrare och utan dyra licensavgifter."}]}]}$j$::jsonb, $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "No – we build on modern tech (Astro/React) and our own e-commerce platform. Faster, more secure and without expensive license fees."}]}]}$j$::jsonb, $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "No: construimos con tecnología moderna (Astro/React) y nuestra propia plataforma de e-commerce. Más rápido, más seguro y sin costosas tarifas de licencia."}]}]}$j$::jsonb, 7),
  ('Vad behöver ni av oss för att börja?', 'What do you need from us to start?', '¿Qué necesitáis de nosotros para empezar?', $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Texter, bilder och logga. Saknas något hjälper vi till med copy, foto och design."}]}]}$j$::jsonb, $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Text, images and a logo. If something's missing we help with copy, photography and design."}]}]}$j$::jsonb, $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Textos, imágenes y un logotipo. Si falta algo, ayudamos con redacción, fotografía y diseño."}]}]}$j$::jsonb, 8),
  ('Vad kostar det per månad?', 'What does it cost per month?', '¿Cuánto cuesta al mes?', $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Hemsidor är en engångskostnad. SEO, GEO, designpartner och e-handel har en löpande månadsavgift."}]}]}$j$::jsonb, $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Websites are a one-off cost. SEO, GEO, design partner and e-commerce have a recurring monthly fee."}]}]}$j$::jsonb, $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Las webs son un coste único. SEO, GEO, socio de diseño y e-commerce tienen una cuota mensual recurrente."}]}]}$j$::jsonb, 9),
  ('Hur fungerar betalningen?', 'How does payment work?', '¿Cómo funciona el pago?', $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Vanligtvis delar vi upp det: en del vid uppstart och resten vid leverans eller lansering. Löpande tjänster (SEO, GEO, designpartner, e-handelsplattform) faktureras månadsvis. Exakta villkor står i offerten."}]}]}$j$::jsonb, $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Typically we split it: part at kick-off and the rest on delivery or launch. Ongoing services (SEO, GEO, design partner, e-commerce platform) are billed monthly. Exact terms are in the quote."}]}]}$j$::jsonb, $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Normalmente lo dividimos: una parte al inicio y el resto en la entrega o el lanzamiento. Los servicios continuos (SEO, GEO, socio de diseño, plataforma de e-commerce) se facturan mensualmente. Las condiciones exactas están en el presupuesto."}]}]}$j$::jsonb, 10),
  ('Får vi support efter lansering?', 'Do we get support after launch?', '¿Tenemos soporte tras el lanzamiento?', $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Ja. En kortare garantiperiod efter lansering ingår, då vi rättar eventuella fel. Därefter erbjuder vi löpande support och förvaltning – till exempel via ett månadspaket eller en designpartner."}]}]}$j$::jsonb, $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Yes. A short warranty period after launch is included, during which we fix any bugs. After that we offer ongoing support and maintenance – for example via a monthly plan or a design partner."}]}]}$j$::jsonb, $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Sí. Tras el lanzamiento se incluye un breve periodo de garantía en el que corregimos posibles errores. Después ofrecemos soporte y mantenimiento continuos, por ejemplo con un plan mensual o un socio de diseño."}]}]}$j$::jsonb, 11),
  ('Kan ni ta över vår befintliga sajt?', 'Can you take over our existing site?', '¿Podéis haceros cargo de nuestro sitio actual?', $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Oftast ja. Vi gör en snabb analys av er nuvarande lösning och föreslår om vi förvaltar den som den är eller bygger om den på vår moderna plattform."}]}]}$j$::jsonb, $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Usually yes. We do a quick analysis of your current setup and advise whether we maintain it as is or rebuild it on our modern platform."}]}]}$j$::jsonb, $j${"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Normalmente sí. Hacemos un análisis rápido de vuestra solución actual y recomendamos si la mantenemos tal cual o la reconstruimos en nuestra plataforma moderna."}]}]}$j$::jsonb, 12)
) AS v(title, title_en, title_es, body, body_en, body_es, ord)
JOIN public.training_categories cat ON cat.slug = 'faq'
WHERE NOT EXISTS (
  SELECT 1 FROM public.training_items ti
  WHERE ti.category_id = cat.id AND ti.title = v.title
);
